name: Update ETH Price

on:
  schedule:
    - cron: "*/5 * * * *" # 매 5분마다 실행
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python fetch_price.py

      - name: Commit and push
        run: |
          git config --global user.name "junhyeok-bot"
          git config --global user.email "junhyeok@example.com"
          git add eth_price.*
          git commit -m "Auto update ETH price"
          git push
